name: dask
channels:
  - defaults
  - conda-forge
dependencies:
  - gcsfs
  - fs-gcsfs
  - jupyterlab
  - jupyter-server-proxy
  - python=3.6
  - numpy
  - h5py
  - scipy
  - toolz
  - bokeh
  - dask
  - distributed
  - notebook
  - matplotlib
  - Pillow
  - pandas
  - pandas-datareader
  - pytables
  - scikit-learn
  - scikit-image
  - snakeviz
  - ujson
  - graphviz
  - pip
  - s3fs
  - fastparquet
  - dask-ml
  - pip:
    - graphviz 
    - cachey
    - azureml-sdk[notebooks]
    - mpi4py
    - gym
    - adlfs